# Generated by Django 3.1.7 on 2021-03-20 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
